version: '2'
services:
  watcher:
    build:
      context: ../
      dockerfile: compose/local/watcher/Dockerfile
    volumes:
      - ../plugins/AldirBlanc:/app
  
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files
      - ../docker-data/pcache-cron.log:/var/www/scripts/nohup.out
      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d

      # themes and plugins
      - ../themes/MapaCulturalCapixaba:/var/www/html/protected/application/themes/MapaCulturalCapixaba
      - ../plugins/AldirBlanc:/var/www/html/protected/application/plugins/AldirBlanc
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth
      - ../plugins/AldirBlancDataprev:/var/www/html/protected/application/plugins/AldirBlancDataprev
      - ../plugins/AldirBlancValidadorFinanceiro:/var/www/html/protected/application/plugins/AldirBlancValidadorFinanceiro
      - ../plugins/RegistrationPayments:/var/www/html/protected/application/plugins/RegistrationPayments
      - ../plugins/AldirBlancValidador:/var/www/html/protected/application/plugins/AldirBlancValidador
      - ../compose/config-cnab240-inciso1.php:/var/www/html/protected/application/plugins/AldirBlanc/config-cnab240-inciso1.php
      - ../compose/config-import-cnab240.php:/var/www/html/protected/application/plugins/AldirBlanc/config-import-cnab240.php
      

    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - APP_MODE=development
      - CACHE_ASSETS_URL=false
      - REDIS_CACHE=redis
      - MAILER_SERVER=mailhog
      - MAILER_PORT=1025
    depends_on:
      - db
      - watcher
      - redis
  
    stdin_open: true
    tty: true

  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ../docker-data/db-data:/var/lib/postgresql/data
