version: '2'
services:
  watcher:
    build:
      context: ../
      dockerfile: compose/local/watcher/Dockerfile
    volumes:
      - ../plugins/AldirBlanc:/app
  
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files
      - ../docker-data/pcache-cron.log:/var/www/scripts/nohup.out

      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d
      - ../../mapasculturais/src/protected/application/themes:/var/www/html/protected/application/themes
      - ../../mapasculturais/src/protected/application/lib:/var/www/html/protected/application/lib
      - ../../mapasculturais/src/protected/db-updates.php:/var/www/html/protected/db-updates.php
      - ../../mapasculturais/src/protected/application/conf/agent-types.php:/var/www/html/protected/application/conf/agent-types.php
      - ../../mapasculturais/src/protected/application/conf/space-types.php:/var/www/html/protected/application/conf/space-types.php

      # themes and plugins
      - ../themes/SampleTheme:/var/www/html/protected/application/themes/SampleTheme
      - ../plugins/AldirBlanc:/var/www/html/protected/application/plugins/AldirBlanc
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth

    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - APP_MODE=development
      - CACHE_ASSETS_URL=false

    depends_on:
      - db
      - watcher
  
    stdin_open: true
    tty: true

  db:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ../docker-data/db-data:/var/lib/postgresql/data

volumes:
  db-data: